/**
 * Unit Tests Results Page
 * 
 * Displays unit test results from Vitest
 * Shows pass/fail counts, test duration, and individual test files
 */

import { CheckCircle, XCircle, Clock, Layers, Wrench, RefreshCw, Info, FileText } from "lucide-react";
import { WexCard, WexTabs, WexAlert } from "@/components/wex";
import { Section } from "@/docs/components/Section";
import { CodeBlock } from "@/docs/components/CodeBlock";

// Import test summary (generated by scripts/generate-unit-test-report.js)
import testSummary from "@/docs/registry/unit-test-summary.json";

interface CategoryData {
  passed: number;
  failed: number;
  total: number;
  files: Array<{
    name: string;
    path: string;
    status: string;
    passed: number;
    failed: number;
    duration: number;
  }>;
}

interface TestSummary {
  _meta: {
    generatedAt: string;
    testRunner: string;
    totalDuration: number;
  };
  totals: {
    suites: number;
    tests: number;
    passed: number;
    failed: number;
    pending: number;
    passRate: number;
  };
  categories: {
    components: CategoryData;
    utils: CategoryData;
    hooks: CategoryData;
  };
  failures: Array<{
    file: string;
    test: string;
    message: string;
  }>;
}

const data = testSummary as TestSummary;

function formatDuration(ms: number): string {
  if (ms < 1000) return `${Math.round(ms)}ms`;
  return `${(ms / 1000).toFixed(2)}s`;
}

// Color-coded category config
const categoryConfig = {
  components: {
    icon: Layers,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
  },
  utils: {
    icon: Wrench,
    color: "text-amber-500",
    bgColor: "bg-amber-500/10",
  },
  hooks: {
    icon: RefreshCw,
    color: "text-violet-500",
    bgColor: "bg-violet-500/10",
  },
} as const;

function CategoryCard({ 
  title, 
  categoryKey,
  category 
}: { 
  title: string; 
  categoryKey: keyof typeof categoryConfig;
  category: CategoryData;
}) {
  const config = categoryConfig[categoryKey];
  const Icon = config.icon;

  return (
    <WexCard className="overflow-hidden">
      <WexCard.Content className="pt-6">
        <div className="flex items-center gap-3 mb-4">
          <div className={`p-2.5 rounded-lg ${config.bgColor}`}>
            <Icon className={`h-5 w-5 ${config.color}`} />
          </div>
          <div>
            <p className="font-semibold text-foreground">{title}</p>
            <p className="text-xs text-muted-foreground">{category.files.length} test files</p>
          </div>
        </div>
        <div className="flex items-baseline gap-3">
          <span className="text-3xl font-bold text-foreground">
            {category.passed}
          </span>
          <span className="text-sm text-muted-foreground">
            / {category.total} tests
          </span>
          {category.passed === category.total && category.total > 0 && (
            <CheckCircle className="h-4 w-4 text-success ml-auto" />
          )}
        </div>
        {category.failed > 0 && (
          <p className="text-sm text-destructive mt-2 flex items-center gap-1">
            <XCircle className="h-3.5 w-3.5" />
            {category.failed} failed
          </p>
        )}
      </WexCard.Content>
    </WexCard>
  );
}

function getTestDepthLabel(count: number): { label: string; color: string } {
  if (count >= 30) return { label: "Comprehensive", color: "bg-green-500/20 text-green-700" };
  if (count >= 15) return { label: "Extended", color: "bg-blue-500/20 text-blue-700" };
  if (count >= 5) return { label: "Standard", color: "bg-muted text-muted-foreground" };
  return { label: "Basic", color: "bg-muted/50 text-muted-foreground" };
}

function FilesList({ files, categoryKey }: { files: CategoryData["files"]; categoryKey: keyof typeof categoryConfig }) {
  const config = categoryConfig[categoryKey];
  const sorted = [...files].sort((a, b) => {
    // Failed first, then by test count (descending), then by name
    if (a.status !== b.status) {
      return a.status === "failed" ? -1 : 1;
    }
    if (a.passed !== b.passed) {
      return b.passed - a.passed; // Higher test count first
    }
    return a.name.localeCompare(b.name);
  });

  return (
    <div className="grid gap-2">
      {sorted.map((file) => {
        const depth = getTestDepthLabel(file.passed);
        return (
          <div 
            key={file.path} 
            className="flex items-center gap-3 p-3 rounded-lg border border-border/50 bg-card hover:bg-muted/30 transition-colors"
          >
            <div className={`p-1.5 rounded ${config.bgColor}`}>
              <FileText className={`h-3.5 w-3.5 ${config.color}`} />
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2">
                <p className="font-mono text-sm truncate text-foreground">{file.name}</p>
                {file.passed >= 15 && (
                  <span className={`text-[10px] px-1.5 py-0.5 rounded font-medium ${depth.color}`}>
                    {depth.label}
                  </span>
                )}
              </div>
              <p className="text-xs text-muted-foreground">
                {file.passed} test{file.passed !== 1 ? 's' : ''} • {formatDuration(file.duration)}
              </p>
            </div>
            {file.status === "passed" ? (
              <CheckCircle className="h-4 w-4 text-success shrink-0" />
            ) : (
              <XCircle className="h-4 w-4 text-destructive shrink-0" />
            )}
          </div>
        );
      })}
    </div>
  );
}

export default function UnitTestsPage() {
  const testedAt = data._meta?.generatedAt 
    ? new Date(data._meta.generatedAt).toLocaleString()
    : "Unknown";

  return (
    <article>
      <header className="mb-10">
        <h1 className="text-3xl font-display font-bold text-foreground mb-2">
          Unit Test Results
        </h1>
        <p className="text-lg text-muted-foreground">
          Test coverage for WEX components, utilities, and hooks using Vitest + React Testing Library.
        </p>
      </header>

      {/* Quick Stats Bar */}
      <Section title="Test Summary" className="mb-16">
        <div className="flex items-center gap-2 mb-6 text-sm text-muted-foreground">
          <Clock className="h-4 w-4" />
          Last run: {testedAt}
        </div>

        <div className="flex flex-wrap items-center gap-6 p-4 rounded-lg bg-muted/30 border border-border/50">
          <div className="flex items-center gap-2">
            <span className="text-2xl font-bold text-foreground">{data.totals.tests}</span>
            <span className="text-sm text-muted-foreground">total tests</span>
          </div>
          <div className="h-8 w-px bg-border hidden sm:block" />
          <div className="flex items-center gap-2">
            <CheckCircle className="h-5 w-5 text-success" />
            <span className="text-2xl font-bold text-success">{data.totals.passed}</span>
            <span className="text-sm text-muted-foreground">passed</span>
          </div>
          {data.totals.failed > 0 && (
            <>
              <div className="h-8 w-px bg-border hidden sm:block" />
              <div className="flex items-center gap-2">
                <XCircle className="h-5 w-5 text-destructive" />
                <span className="text-2xl font-bold text-destructive">{data.totals.failed}</span>
                <span className="text-sm text-muted-foreground">failed</span>
              </div>
            </>
          )}
          <div className="h-8 w-px bg-border hidden sm:block" />
          <div className="flex items-center gap-2">
            <span className="text-2xl font-bold text-foreground">{data.totals.passRate}%</span>
            <span className="text-sm text-muted-foreground">pass rate</span>
          </div>
        </div>
      </Section>

      {/* Test Coverage Notes */}
      <Section title="Test Coverage Notes" className="mb-16">
        <WexAlert>
          <Info className="h-4 w-4" />
          <WexAlert.Title>Comprehensive Test Coverage</WexAlert.Title>
          <WexAlert.Description>
            These tests provide <strong>comprehensive coverage</strong> including rendering, prop forwarding, 
            user interactions, keyboard navigation, state management, form integration, and accessibility attributes. 
            Core interactive components (Button, Input, Checkbox, Switch, Dialog, Sheet, Tabs, Accordion, Select, 
            Combobox, Dropdown, Tooltip, Popover, Radio Group, Slider) have extensive test suites covering 
            click handlers, keyboard events, controlled/uncontrolled modes, disabled states, and ARIA compliance.
          </WexAlert.Description>
        </WexAlert>

        <div className="mt-6 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <div className="p-4 rounded-lg border border-border bg-muted/30">
            <p className="text-sm font-medium mb-1">Interactions</p>
            <p className="text-xs text-muted-foreground">Click, toggle, open/close behaviors</p>
          </div>
          <div className="p-4 rounded-lg border border-border bg-muted/30">
            <p className="text-sm font-medium mb-1">Keyboard Navigation</p>
            <p className="text-xs text-muted-foreground">Arrow keys, Tab, Enter, Escape</p>
          </div>
          <div className="p-4 rounded-lg border border-border bg-muted/30">
            <p className="text-sm font-medium mb-1">State Management</p>
            <p className="text-xs text-muted-foreground">Controlled/uncontrolled, callbacks</p>
          </div>
          <div className="p-4 rounded-lg border border-border bg-muted/30">
            <p className="text-sm font-medium mb-1">Form Integration</p>
            <p className="text-xs text-muted-foreground">Name, value, required attributes</p>
          </div>
          <div className="p-4 rounded-lg border border-border bg-muted/30">
            <p className="text-sm font-medium mb-1">Accessibility</p>
            <p className="text-xs text-muted-foreground">ARIA roles, labels, states</p>
          </div>
          <div className="p-4 rounded-lg border border-border bg-muted/30">
            <p className="text-sm font-medium mb-1">Edge Cases</p>
            <p className="text-xs text-muted-foreground">Rapid actions, empty states, limits</p>
          </div>
        </div>
      </Section>

      {/* Category Breakdown */}
      <Section title="Test Categories" className="mb-16">
        <p className="text-muted-foreground mb-6">
          Tests are organized into three categories. Component tests cover rendering, interactions, 
          keyboard navigation, and accessibility. Utility tests validate helper functions. Hook tests 
          verify custom React hooks.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <CategoryCard 
            title="Components" 
            categoryKey="components"
            category={data.categories.components} 
          />
          <CategoryCard 
            title="Utilities" 
            categoryKey="utils"
            category={data.categories.utils} 
          />
          <CategoryCard 
            title="Hooks" 
            categoryKey="hooks"
            category={data.categories.hooks} 
          />
        </div>
      </Section>

      {/* Test Files */}
      <Section title="Test Files" className="mb-16">
        <p className="text-muted-foreground mb-6">
          Individual test files sorted by coverage depth. Files with <span className="px-1.5 py-0.5 rounded text-xs bg-green-500/20 text-green-700 font-medium">Comprehensive</span> coverage 
          (30+ tests) include interactions, keyboard navigation, state management, and accessibility tests.
          <span className="px-1.5 py-0.5 rounded text-xs bg-blue-500/20 text-blue-700 font-medium ml-1">Extended</span> coverage 
          (15+ tests) includes most test categories.
        </p>
        <WexTabs defaultValue="components" className="w-full">
          <WexTabs.List className="mb-6">
            <WexTabs.Trigger value="components" className="gap-2">
              <Layers className="h-4 w-4 text-blue-500" />
              Components ({data.categories.components.total} tests)
            </WexTabs.Trigger>
            <WexTabs.Trigger value="utils" className="gap-2">
              <Wrench className="h-4 w-4 text-amber-500" />
              Utilities ({data.categories.utils.total} tests)
            </WexTabs.Trigger>
            <WexTabs.Trigger value="hooks" className="gap-2">
              <RefreshCw className="h-4 w-4 text-violet-500" />
              Hooks ({data.categories.hooks.total} tests)
            </WexTabs.Trigger>
            {data.failures.length > 0 && (
              <WexTabs.Trigger value="failures" className="text-destructive gap-2">
                <XCircle className="h-4 w-4" />
                Failures ({data.failures.length})
              </WexTabs.Trigger>
            )}
          </WexTabs.List>

          <WexTabs.Content value="components">
            <FilesList files={data.categories.components.files} categoryKey="components" />
          </WexTabs.Content>

          <WexTabs.Content value="utils">
            <FilesList files={data.categories.utils.files} categoryKey="utils" />
          </WexTabs.Content>

          <WexTabs.Content value="hooks">
            <FilesList files={data.categories.hooks.files} categoryKey="hooks" />
          </WexTabs.Content>

          {data.failures.length > 0 && (
            <WexTabs.Content value="failures">
              <div className="space-y-4">
                {data.failures.map((failure, i) => (
                  <WexCard key={i} className="border-destructive/30">
                    <WexCard.Header className="pb-2">
                      <div className="flex items-center gap-2">
                        <XCircle className="h-4 w-4 text-destructive" />
                        <WexCard.Title className="text-sm font-mono">
                          {failure.file}
                        </WexCard.Title>
                      </div>
                    </WexCard.Header>
                    <WexCard.Content>
                      <p className="text-sm font-medium mb-2">{failure.test}</p>
                      <p className="text-xs text-muted-foreground font-mono bg-muted p-2 rounded overflow-x-auto">
                        {failure.message}
                      </p>
                    </WexCard.Content>
                  </WexCard>
                ))}
              </div>
            </WexTabs.Content>
          )}
        </WexTabs>
      </Section>

      {/* How to Run */}
      <Section title="How to Run Tests">
        <div className="space-y-6">
          <p className="text-muted-foreground">
            Run unit tests locally using the following commands:
          </p>

          <div className="space-y-4">
            <div>
              <p className="text-sm font-medium mb-2">Run all tests once:</p>
              <CodeBlock code="npm run test:unit" language="bash" />
            </div>

            <div>
              <p className="text-sm font-medium mb-2">Run tests in watch mode:</p>
              <CodeBlock code="npm run test:unit:watch" language="bash" />
            </div>

            <div>
              <p className="text-sm font-medium mb-2">Generate test report:</p>
              <CodeBlock code="npm run test:unit:report" language="bash" />
            </div>
          </div>

          <p className="text-sm text-muted-foreground mt-4">
            Tests are written using <strong>Vitest</strong> with{" "}
            <strong>React Testing Library</strong>. Test files are located in{" "}
            <code className="px-1.5 py-0.5 bg-muted rounded text-xs">tests/</code>.
          </p>
        </div>
      </Section>
    </article>
  );
}
