import type { ComponentRegistryEntry } from "./types";

/**
 * Component registry - drives navigation and route generation
 *
 * All components are Wex-prefixed (Pattern A architecture).
 * Import components from @/components/wex, NOT @/components/ui.
 *
 * STATUS DEFINITIONS:
 * - stable: Production-ready, fully documented
 * - beta: API may change, mostly documented
 * - alpha: Experimental, minimal documentation
 *
 * CATEGORY DEFINITIONS:
 * - actions: Interactive elements that trigger behavior (Button, Toggle)
 * - form-inputs: Data entry components (Input, Select, Checkbox)
 * - form-structure: Form organization (Field, Form, Label)
 * - layout: Structural components (Card, Accordion, Separator)
 * - data-display: Presenting information (Table, Badge, Avatar)
 * - feedback: Communicate status (Alert, Progress, Spinner)
 * - navigation: Move between views (Breadcrumb, Tabs, Pagination)
 * - overlays: Floating/modal elements (Dialog, Popover, Tooltip)
 *
 * WCAG COMPLIANCE:
 * - Most components target WCAG 2.2 AA
 * - Alpha components may have partial compliance
 *
 * NOTE: Display names in nav do NOT include "Wex" prefix for readability.
 * In code, always use the Wex-prefixed component names (e.g., WexButton).
 */
export const componentRegistry: ComponentRegistryEntry[] = [
  // ===== ACTIONS =====
  {
    name: "Button",
    route: "/components/button",
    importPath: "@/docs/pages/components/ButtonPage",
    description: "Primary interactive element for user actions",
    status: "stable",
    category: "actions",
    tags: ["action", "form"],
  },
  {
    name: "Button Group",
    route: "/components/button-group",
    importPath: "@/docs/pages/components/ButtonGroupPage",
    description: "Container for grouping related buttons",
    status: "stable",
    category: "actions",
    tags: ["action", "layout"],
  },
  {
    name: "Toggle",
    route: "/components/toggle",
    importPath: "@/docs/pages/components/TogglePage",
    description: "Two-state button",
    status: "stable",
    category: "actions",
    tags: ["action", "form"],
  },
  {
    name: "Toggle Group",
    route: "/components/toggle-group",
    importPath: "@/docs/pages/components/ToggleGroupPage",
    description: "Set of two-state buttons",
    status: "stable",
    category: "actions",
    tags: ["action", "form"],
  },

  // ===== FORM INPUTS =====
  {
    name: "Calendar",
    route: "/components/calendar",
    importPath: "@/docs/pages/components/CalendarPage",
    description: "Date picker calendar component",
    status: "stable",
    category: "form-inputs",
    tags: ["form", "date"],
  },
  {
    name: "Checkbox",
    route: "/components/checkbox",
    importPath: "@/docs/pages/components/CheckboxPage",
    description: "Control for toggling boolean values",
    status: "stable",
    category: "form-inputs",
    tags: ["form", "input"],
  },
  {
    name: "Combobox",
    route: "/components/combobox",
    importPath: "@/docs/pages/components/ComboboxPage",
    description: "Autocomplete input with search and dropdown selection",
    status: "stable",
    category: "form-inputs",
    tags: ["form", "input", "autocomplete"],
  },
  {
    name: "Date Picker",
    route: "/components/date-picker",
    importPath: "@/docs/pages/components/DatePickerPage",
    description: "Date selection input with calendar popover",
    status: "stable",
    category: "form-inputs",
    tags: ["form", "input", "date"],
  },
  {
    name: "Float Label",
    route: "/components/float-label",
    importPath: "@/docs/pages/components/FloatLabelPage",
    description: "Input with floating label that animates on focus",
    status: "stable",
    category: "form-inputs",
    tags: ["form", "input"],
  },
  {
    name: "Input",
    route: "/components/input",
    importPath: "@/docs/pages/components/InputPage",
    description: "Text input field for forms",
    status: "stable",
    category: "form-inputs",
    tags: ["form", "input"],
  },
  {
    name: "Input Group",
    route: "/components/input-group",
    importPath: "@/docs/pages/components/InputGroupPage",
    description: "Input with addons and buttons",
    status: "stable",
    category: "form-inputs",
    tags: ["form", "input"],
  },
  {
    name: "Input OTP",
    route: "/components/input-otp",
    importPath: "@/docs/pages/components/InputOTPPage",
    description: "One-time password input",
    status: "stable",
    category: "form-inputs",
    tags: ["form", "input"],
  },
  {
    name: "Radio Group",
    route: "/components/radio-group",
    importPath: "@/docs/pages/components/RadioGroupPage",
    description: "Set of checkable radio buttons",
    status: "stable",
    category: "form-inputs",
    tags: ["form", "input"],
  },
  {
    name: "Select",
    route: "/components/select",
    importPath: "@/docs/pages/components/SelectPage",
    description: "Dropdown selection control",
    status: "stable",
    category: "form-inputs",
    tags: ["form", "input"],
  },
  {
    name: "Slider",
    route: "/components/slider",
    importPath: "@/docs/pages/components/SliderPage",
    description: "Range input for selecting values",
    status: "stable",
    category: "form-inputs",
    tags: ["form", "input"],
  },
  {
    name: "Switch",
    route: "/components/switch",
    importPath: "@/docs/pages/components/SwitchPage",
    description: "Toggle between two states",
    status: "stable",
    category: "form-inputs",
    tags: ["form", "input"],
  },
  {
    name: "Textarea",
    route: "/components/textarea",
    importPath: "@/docs/pages/components/TextareaPage",
    description: "Multi-line text input",
    status: "stable",
    category: "form-inputs",
    tags: ["form", "input"],
  },

  // ===== FORM STRUCTURE =====
  {
    name: "Field",
    route: "/components/field",
    importPath: "@/docs/pages/components/FieldPage",
    description: "Form field container with label and error handling",
    status: "stable",
    category: "form-structure",
    tags: ["form"],
  },
  {
    name: "Form",
    route: "/components/form",
    importPath: "@/docs/pages/components/FormPage",
    description: "Form handling with validation",
    status: "stable",
    category: "form-structure",
    tags: ["form"],
  },
  {
    name: "Label",
    route: "/components/label",
    importPath: "@/docs/pages/components/LabelPage",
    description: "Accessible label for form controls",
    status: "stable",
    category: "form-structure",
    tags: ["form", "accessibility"],
  },

  // ===== LAYOUT =====
  {
    name: "Accordion",
    route: "/components/accordion",
    importPath: "@/docs/pages/components/AccordionPage",
    description: "Vertically stacked set of interactive headings",
    status: "stable",
    category: "layout",
    tags: ["disclosure", "layout"],
  },
  {
    name: "Aspect Ratio",
    route: "/components/aspect-ratio",
    importPath: "@/docs/pages/components/AspectRatioPage",
    description: "Displays content within a desired ratio",
    status: "stable",
    category: "layout",
    tags: ["layout", "media"],
  },
  {
    name: "Card",
    route: "/components/card",
    importPath: "@/docs/pages/components/CardPage",
    description: "Container for grouping related content",
    status: "stable",
    category: "layout",
    tags: ["layout", "container"],
  },
  {
    name: "Collapsible",
    route: "/components/collapsible",
    importPath: "@/docs/pages/components/CollapsiblePage",
    description: "Expandable/collapsible content section",
    status: "stable",
    category: "layout",
    tags: ["disclosure", "layout"],
  },
  {
    name: "Resizable",
    route: "/components/resizable",
    importPath: "@/docs/pages/components/ResizablePage",
    description: "Resizable panel groups",
    status: "stable",
    category: "layout",
    tags: ["layout"],
  },
  {
    name: "Scroll Area",
    route: "/components/scroll-area",
    importPath: "@/docs/pages/components/ScrollAreaPage",
    description: "Custom scrollable viewport",
    status: "stable",
    category: "layout",
    tags: ["layout"],
  },
  {
    name: "Separator",
    route: "/components/separator",
    importPath: "@/docs/pages/components/SeparatorPage",
    description: "Visual divider between content",
    status: "stable",
    category: "layout",
    tags: ["layout"],
  },

  // ===== DATA DISPLAY =====
  {
    name: "Avatar",
    route: "/components/avatar",
    importPath: "@/docs/pages/components/AvatarPage",
    description: "Image element with fallback for user profiles",
    status: "stable",
    category: "data-display",
    tags: ["display", "user"],
  },
  {
    name: "Badge",
    route: "/components/badge",
    importPath: "@/docs/pages/components/BadgePage",
    description: "Small status descriptor for UI elements",
    status: "stable",
    category: "data-display",
    tags: ["display", "status"],
  },
  {
    name: "Carousel",
    route: "/components/carousel",
    importPath: "@/docs/pages/components/CarouselPage",
    description: "Slideshow for cycling through elements",
    status: "stable",
    category: "data-display",
    tags: ["display", "media"],
  },
  {
    name: "Chart",
    route: "/components/chart",
    importPath: "@/docs/pages/components/ChartPage",
    description: "Data visualization components (chart tokens are placeholders)",
    status: "alpha",
    category: "data-display",
    tags: ["data", "visualization"],
  },
  {
    name: "Data Table",
    route: "/components/data-table",
    importPath: "@/docs/pages/components/DataTablePage",
    description: "Advanced table with sorting, filtering, and pagination",
    status: "stable",
    category: "data-display",
    tags: ["data", "table"],
  },
  {
    name: "Empty",
    route: "/components/empty",
    importPath: "@/docs/pages/components/EmptyPage",
    description: "Empty state placeholder",
    status: "stable",
    category: "data-display",
    tags: ["display", "feedback"],
  },
  {
    name: "Item",
    route: "/components/item",
    importPath: "@/docs/pages/components/ItemPage",
    description: "Flexible list item component",
    status: "stable",
    category: "data-display",
    tags: ["display", "layout"],
  },
  {
    name: "Kbd",
    route: "/components/kbd",
    importPath: "@/docs/pages/components/KbdPage",
    description: "Keyboard key display",
    status: "stable",
    category: "data-display",
    tags: ["display"],
  },
  {
    name: "Table",
    route: "/components/table",
    importPath: "@/docs/pages/components/TablePage",
    description: "Tabular data display",
    status: "stable",
    category: "data-display",
    tags: ["data", "display"],
  },

  // ===== FEEDBACK =====
  {
    name: "Alert",
    route: "/components/alert",
    importPath: "@/docs/pages/components/AlertPage",
    description: "Displays important messages to users",
    status: "stable",
    category: "feedback",
    tags: ["feedback", "notification"],
  },
  {
    name: "Progress",
    route: "/components/progress",
    importPath: "@/docs/pages/components/ProgressPage",
    description: "Progress indicator for tasks",
    status: "stable",
    category: "feedback",
    tags: ["feedback", "loading"],
  },
  {
    name: "Skeleton",
    route: "/components/skeleton",
    importPath: "@/docs/pages/components/SkeletonPage",
    description: "Loading placeholder for content",
    status: "stable",
    category: "feedback",
    tags: ["feedback", "loading"],
  },
  {
    name: "Sonner",
    route: "/components/sonner",
    importPath: "@/docs/pages/components/SonnerPage",
    description: "Opinionated toast component (top-center, stacking)",
    status: "stable",
    category: "feedback",
    tags: ["feedback", "notification"],
  },
  {
    name: "Spinner",
    route: "/components/spinner",
    importPath: "@/docs/pages/components/SpinnerPage",
    description: "Loading spinner indicator",
    status: "stable",
    category: "feedback",
    tags: ["feedback", "loading"],
  },
  {
    name: "Toast",
    route: "/components/toast",
    importPath: "@/docs/pages/components/ToastPage",
    description: "Toast notifications (quick reference)",
    status: "beta",
    category: "feedback",
    tags: ["feedback", "notification"],
  },

  // ===== NAVIGATION =====
  {
    name: "Breadcrumb",
    route: "/components/breadcrumb",
    importPath: "@/docs/pages/components/BreadcrumbPage",
    description: "Navigation showing current location hierarchy",
    status: "stable",
    category: "navigation",
    tags: ["navigation"],
  },
  {
    name: "Command",
    route: "/components/command",
    importPath: "@/docs/pages/components/CommandPage",
    description: "Command palette for keyboard-first navigation",
    status: "stable",
    category: "navigation",
    tags: ["navigation", "search"],
  },
  {
    name: "Menubar",
    route: "/components/menubar",
    importPath: "@/docs/pages/components/MenubarPage",
    description: "Horizontal menu bar for app navigation",
    status: "stable",
    category: "navigation",
    tags: ["menu", "navigation"],
  },
  {
    name: "Navigation Menu",
    route: "/components/navigation-menu",
    importPath: "@/docs/pages/components/NavigationMenuPage",
    description: "Collection of navigation links",
    status: "stable",
    category: "navigation",
    tags: ["navigation", "menu"],
  },
  {
    name: "Pagination",
    route: "/components/pagination",
    importPath: "@/docs/pages/components/PaginationPage",
    description: "Navigation for multi-page content",
    status: "stable",
    category: "navigation",
    tags: ["navigation"],
  },
  {
    name: "Sidebar",
    route: "/components/sidebar",
    importPath: "@/docs/pages/components/SidebarPage",
    description: "Collapsible navigation sidebar",
    status: "stable",
    category: "navigation",
    tags: ["navigation", "layout"],
  },
  {
    name: "Tabs",
    route: "/components/tabs",
    importPath: "@/docs/pages/components/TabsPage",
    description: "Tabbed content panels",
    status: "stable",
    category: "navigation",
    tags: ["navigation", "layout"],
  },

  // ===== OVERLAYS =====
  {
    name: "Alert Dialog",
    route: "/components/alert-dialog",
    importPath: "@/docs/pages/components/AlertDialogPage",
    description: "Modal dialog for important confirmations",
    status: "stable",
    category: "overlays",
    tags: ["overlay", "modal"],
  },
  {
    name: "Context Menu",
    route: "/components/context-menu",
    importPath: "@/docs/pages/components/ContextMenuPage",
    description: "Right-click context menu for actions",
    status: "stable",
    category: "overlays",
    tags: ["menu", "overlay"],
  },
  {
    name: "Dialog",
    route: "/components/dialog",
    importPath: "@/docs/pages/components/DialogPage",
    description: "Modal dialog for focused content",
    status: "stable",
    category: "overlays",
    tags: ["overlay", "modal"],
  },
  {
    name: "Drawer",
    route: "/components/drawer",
    importPath: "@/docs/pages/components/DrawerPage",
    description: "Slide-out panel for mobile navigation",
    status: "stable",
    category: "overlays",
    tags: ["overlay", "navigation"],
  },
  {
    name: "Dropdown Menu",
    route: "/components/dropdown-menu",
    importPath: "@/docs/pages/components/DropdownMenuPage",
    description: "Menu triggered by a button",
    status: "stable",
    category: "overlays",
    tags: ["menu", "overlay"],
  },
  {
    name: "Hover Card",
    route: "/components/hover-card",
    importPath: "@/docs/pages/components/HoverCardPage",
    description: "Preview content on hover",
    status: "stable",
    category: "overlays",
    tags: ["overlay", "tooltip"],
  },
  {
    name: "Popover",
    route: "/components/popover",
    importPath: "@/docs/pages/components/PopoverPage",
    description: "Floating content triggered by a button",
    status: "stable",
    category: "overlays",
    tags: ["overlay"],
  },
  {
    name: "Sheet",
    route: "/components/sheet",
    importPath: "@/docs/pages/components/SheetPage",
    description: "Slide-out panel from screen edge",
    status: "stable",
    category: "overlays",
    tags: ["overlay", "navigation"],
  },
  {
    name: "Tooltip",
    route: "/components/tooltip",
    importPath: "@/docs/pages/components/TooltipPage",
    description: "Popup info on hover/focus",
    status: "stable",
    category: "overlays",
    tags: ["overlay", "tooltip"],
  },
];
